query User($id: ID!) { 
  user(id: $id) {
    id
    first_name
    last_name
    full_name
    initials
    email
    street
    postcode
    city
    country
    created_at
    updated_at
    login_at

    groups {
      id
      name
    }
  }
}